# Author: Jesus Ponte
# Fecha: 15/09/2023
# Ejercicio 4. Modelo de clasificación con Keras


## Importación de librerias
### Se utiliza numpy para hacer la creación de la data random, manejo de los arrays, hacer shuffle de la data.
### Sklearn para hacer la separación de la data a train, test
### Keras para la creación de la red neuronal y las capas. 


In [265]:
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
#No uso pandas porque no haré limpieza de datos en general. 

### Creación de la data random para las compras medianas

In [266]:
np.random.seed(333)

med_low = 11
med_high = 20
n_samples = 1000

rng_med = np.random.uniform(low = med_low,high = med_high,size= (n_samples, 4))
list = []

for row in rng_med:
    list.append( [np.random.uniform(max(row), med_high)])
rng_med = np.append(rng_med, list, axis=1)
rng_med[:, 0] = np.random.randint(1,10,n_samples)


### Creación de la data random para las compras pequeñas


In [267]:
low_low = 1
low_high = 10

rng_low = np.random.uniform(low = low_low,high = low_high,size= (n_samples, 4))
list = []

for row in rng_low:
    list.append( [np.random.uniform(max(row), low_high)])
rng_low = np.append(rng_low, list, axis=1)
rng_low[:, 0] = np.random.randint(1,10,n_samples)

### Creación de la data random para las compras grandes


In [268]:
high_low = 21
high_high = 30

rng_high = np.random.uniform(low = high_low, high = high_high, size= (n_samples, 4))
list = []

for row in rng_high:
    list.append( [np.random.uniform(max(row), high_high)])
rng_high = np.append(rng_high, list, axis=1)
rng_high[:, 0] = np.random.randint(1,10,n_samples)

In [269]:
rng_med

array([[ 2.        , 17.56055655, 11.15193301, 13.97304923, 17.59518743],
       [ 6.        , 11.43473299, 11.94077169, 11.87693764, 17.3944537 ],
       [ 4.        , 18.86140419, 11.46450475, 11.54433202, 19.46905195],
       ...,
       [ 4.        , 12.91925794, 13.21955606, 13.62179205, 19.37036117],
       [ 4.        , 15.65889737, 18.01012532, 18.35458078, 19.83299465],
       [ 2.        , 12.74743122, 17.98777563, 13.73634595, 19.14762349]])

In [270]:
rng_low

array([[6.        , 8.03217632, 8.52973323, 4.16977679, 8.89817662],
       [1.        , 6.9881703 , 5.51239991, 8.11898087, 9.79409963],
       [5.        , 5.69055765, 1.60896424, 8.48162857, 9.72490114],
       ...,
       [7.        , 7.81347441, 7.34466964, 1.10104672, 9.07062656],
       [7.        , 4.37344452, 4.3505672 , 9.21694486, 9.42416774],
       [1.        , 9.11248288, 5.08554487, 9.93419801, 9.95509892]])

In [271]:
rng_high

array([[ 9.        , 27.93983489, 23.02371397, 28.35584981, 28.79973221],
       [ 9.        , 23.97186544, 25.42886019, 22.67645848, 26.48657905],
       [ 8.        , 27.98322768, 26.52426546, 26.58187201, 28.86926336],
       ...,
       [ 2.        , 27.69929217, 22.81577766, 27.00310881, 28.78735209],
       [ 2.        , 24.0582314 , 25.6140638 , 25.10506824, 29.6338751 ],
       [ 1.        , 28.40784474, 29.50818809, 28.1817416 , 29.76460037]])

### Unión de las tres matrices para la creación de una tabla monolitica

In [272]:
sales = np.vstack([rng_low, rng_med, rng_high])

In [273]:
sales

array([[ 6.        ,  8.03217632,  8.52973323,  4.16977679,  8.89817662],
       [ 1.        ,  6.9881703 ,  5.51239991,  8.11898087,  9.79409963],
       [ 5.        ,  5.69055765,  1.60896424,  8.48162857,  9.72490114],
       ...,
       [ 2.        , 27.69929217, 22.81577766, 27.00310881, 28.78735209],
       [ 2.        , 24.0582314 , 25.6140638 , 25.10506824, 29.6338751 ],
       [ 1.        , 28.40784474, 29.50818809, 28.1817416 , 29.76460037]])

In [274]:
labels = np.array([0] * n_samples + [1] * n_samples + [2] * n_samples)

In [275]:
shuffle = np.arange(sales.shape[0])
np.random.shuffle(shuffle)

In [276]:
data = sales[shuffle]
labels = labels[shuffle]

In [277]:
X_train, X_test, y_train, y_test = train_test_split(data, labels, test_size=0.2, random_state=50)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [278]:
model = Sequential()
model.add(Dense(32, activation='relu', input_dim=5))

model.add(Dense(32, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(3, activation='softmax'))

model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=5, batch_size=300, validation_split=0.2)

Epoch 1/5
7/7 [==============================] - 1s 17ms/step - loss: 1.1756 - accuracy: 0.3990 - val_loss: 1.1003 - val_accuracy: 0.5208
Epoch 2/5
7/7 [==============================] - 0s 4ms/step - loss: 1.0462 - accuracy: 0.5583 - val_loss: 0.9869 - val_accuracy: 0.5813
Epoch 3/5
7/7 [==============================] - 0s 4ms/step - loss: 0.9390 - accuracy: 0.7661 - val_loss: 0.8846 - val_accuracy: 0.8188
Epoch 4/5
7/7 [==============================] - 0s 4ms/step - loss: 0.8394 - accuracy: 0.8318 - val_loss: 0.7895 - val_accuracy: 0.8042
Epoch 5/5
7/7 [==============================] - 0s 4ms/step - loss: 0.7450 - accuracy: 0.8245 - val_loss: 0.6963 - val_accuracy: 0.8000


In [279]:
loss, accuracy = model.evaluate(X_test, y_test)
print('loss: '+ str(loss))
print('accuracy: '+ str(accuracy*100))

19/19 [==============================] - 0s 614us/step - loss: 0.6764 - accuracy: 0.8317
loss: 0.6764496564865112
accuracy: 83.1666648387909
