# Author: Jesus Ponte
# Fecha: 15/09/2023
# Ejercicio 4. Modelo de clasificación con Keras


## Importación de librerias
### Se utiliza numpy para hacer la creación de la data random, manejo de los arrays, hacer shuffle de la data.
### Sklearn para hacer la separación de la data a train, test
### Keras para la creación de la red neuronal y las capas. 


In [209]:
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
#No uso pandas porque no haré limpieza de datos en general. 

### Creación de la data random para las compras medianas

In [210]:
np.random.seed(333)

med_low = 110
med_high = 200
n_samples = 1000

rng_med = np.random.uniform(low = med_low,high = med_high,size= (n_samples, 4))
list = []

for row in rng_med:
    list.append( [np.random.uniform(max(row), med_high)])
rng_med = np.append(rng_med, list, axis=1)
rng_med[:, 0] = np.random.randint(1,10,n_samples)


### Creación de la data random para las compras pequeñas


In [211]:
low_low = 1
low_high = 109

rng_low = np.random.uniform(low = low_low,high = low_high,size= (n_samples, 4))
list = []

for row in rng_low:
    list.append( [np.random.uniform(max(row), low_high)])
rng_low = np.append(rng_low, list, axis=1)
rng_low[:, 0] = np.random.randint(1,10,n_samples)

### Creación de la data random para las compras grandes


In [212]:
high_low = 201
high_high = 300

rng_high = np.random.uniform(low = high_low, high = high_high, size= (n_samples, 4))
list = []

for row in rng_high:
    list.append( [np.random.uniform(max(row), high_high)])
rng_high = np.append(rng_high, list, axis=1)
rng_high[:, 0] = np.random.randint(1,10,n_samples)

In [213]:
rng_med

array([[  2.        , 175.60556551, 111.51933014, 139.73049226,
        175.95187433],
       [  6.        , 114.34732992, 119.40771694, 118.76937641,
        173.94453699],
       [  4.        , 188.6140419 , 114.64504754, 115.44332022,
        194.69051949],
       ...,
       [  4.        , 129.19257939, 132.19556061, 136.21792055,
        193.70361172],
       [  4.        , 156.5889737 , 180.10125321, 183.54580779,
        198.32994646],
       [  2.        , 127.47431218, 179.8777563 , 137.36345949,
        191.47623487]])

In [214]:
rng_low

array([[  6.        ,  85.3861158 ,  91.35679873,  39.03732154,
         95.77811947],
       [  1.        ,  72.85804365,  55.14879886,  86.42777047,
        106.52919557],
       [  5.        ,  57.28669178,   8.3075709 ,  90.77954282,
        105.69881373],
       ...,
       [  7.        ,  82.76169293,  77.1360357 ,   2.21256067,
         97.84751877],
       [  7.        ,  41.48133428,  41.2068064 ,  99.60333836,
        102.0900129 ],
       [  1.        ,  98.34979452,  50.02653847, 108.21037614,
        108.46118704]])

In [215]:
rng_high

array([[  9.        , 277.3381838 , 223.26085368, 281.9143479 ,
        286.79705436],
       [  9.        , 233.69051989, 249.71746214, 219.44104326,
        261.35236956],
       [  8.        , 277.81550448, 261.76692006, 262.40059215,
        287.56189694],
       ...,
       [  2.        , 274.69221385, 220.97355425, 267.03419693,
        286.66087294],
       [  2.        , 234.6405454 , 251.75470178, 246.15575064,
        295.97262614],
       [  1.        , 282.48629217, 294.59006904, 279.99915757,
        297.41060408]])

### Unión de las tres matrices para la creación de una tabla monolitica

In [216]:
sales = np.vstack([rng_low, rng_med, rng_high])

In [217]:
sales

array([[  6.        ,  85.3861158 ,  91.35679873,  39.03732154,
         95.77811947],
       [  1.        ,  72.85804365,  55.14879886,  86.42777047,
        106.52919557],
       [  5.        ,  57.28669178,   8.3075709 ,  90.77954282,
        105.69881373],
       ...,
       [  2.        , 274.69221385, 220.97355425, 267.03419693,
        286.66087294],
       [  2.        , 234.6405454 , 251.75470178, 246.15575064,
        295.97262614],
       [  1.        , 282.48629217, 294.59006904, 279.99915757,
        297.41060408]])

In [218]:
labels = np.array([0] * n_samples + [1] * n_samples + [2] * n_samples)

In [219]:
shuffle = np.arange(sales.shape[0])
np.random.shuffle(shuffle)

In [220]:
data = sales[shuffle]
labels = labels[shuffle]

In [221]:
X_train, X_test, y_train, y_test = train_test_split(data, labels, test_size=0.2, random_state=50)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [222]:
model = Sequential()
model.add(Dense(32, activation='relu', input_dim=5))

model.add(Dense(32, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(3, activation='softmax'))

model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])


### Test 1. Epochs=5, batch_size=300, validation_split=0.2

In [223]:
model.fit(X_train, y_train, epochs=5, batch_size=300, validation_split=0.2)
loss, accuracy = model.evaluate(X_test, y_test)
print('loss: '+ str(loss))
print('accuracy: '+ str(accuracy*100))

Epoch 1/5
7/7 [==============================] - 1s 18ms/step - loss: 1.0564 - accuracy: 0.5536 - val_loss: 0.9858 - val_accuracy: 0.7354
Epoch 2/5
7/7 [==============================] - 0s 4ms/step - loss: 0.9401 - accuracy: 0.7880 - val_loss: 0.8892 - val_accuracy: 0.7937
Epoch 3/5
7/7 [==============================] - 0s 4ms/step - loss: 0.8473 - accuracy: 0.8073 - val_loss: 0.8040 - val_accuracy: 0.8167
Epoch 4/5
7/7 [==============================] - 0s 4ms/step - loss: 0.7598 - accuracy: 0.8229 - val_loss: 0.7159 - val_accuracy: 0.8313
Epoch 5/5
19/19 [==============================] - 0s 638us/step - loss: 0.5993 - accuracy: 0.8833
loss: 0.5993263125419617
accuracy: 88.33333253860474


### Test 2. Epochs=10, batch_size=350, validation_split=0.25

In [224]:
model = Sequential()
model.add(Dense(32, activation='relu', input_dim=5))

model.add(Dense(32, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(3, activation='softmax'))

model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=10, batch_size=350, validation_split=0.25)
loss, accuracy = model.evaluate(X_test, y_test)
print('loss: '+ str(loss))
print('accuracy: '+ str(accuracy*100))

Epoch 1/10
6/6 [==============================] - 1s 22ms/step - loss: 1.0338 - accuracy: 0.5528 - val_loss: 0.9670 - val_accuracy: 0.7483
Epoch 2/10
6/6 [==============================] - 0s 5ms/step - loss: 0.9368 - accuracy: 0.7872 - val_loss: 0.8749 - val_accuracy: 0.8050
Epoch 3/10
6/6 [==============================] - 0s 4ms/step - loss: 0.8444 - accuracy: 0.8111 - val_loss: 0.7831 - val_accuracy: 0.8133
Epoch 4/10
6/6 [==============================] - 0s 5ms/step - loss: 0.7511 - accuracy: 0.8200 - val_loss: 0.6891 - val_accuracy: 0.8167
Epoch 5/10
6/6 [==============================] - 0s 4ms/step - loss: 0.6579 - accuracy: 0.8261 - val_loss: 0.6003 - val_accuracy: 0.8200
Epoch 6/10
6/6 [==============================] - 0s 5ms/step - loss: 0.5730 - accuracy: 0.8372 - val_loss: 0.5224 - val_accuracy: 0.8450
Epoch 7/10
6/6 [==============================] - 0s 5ms/step - loss: 0.4986 - accuracy: 0.8644 - val_loss: 0.4574 - val_accuracy: 0.8667
Epoch 8/10
6/6 [=================

### Test 3. Epochs=10, batch_size=100, validation_split=0.15


In [225]:
model = Sequential()
model.add(Dense(32, activation='relu', input_dim=5))

model.add(Dense(32, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(3, activation='softmax'))

model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=10, batch_size=100, validation_split=0.15)
loss, accuracy = model.evaluate(X_test, y_test)
print('loss: '+ str(loss))
print('accuracy: '+ str(accuracy*100))

Epoch 1/10
21/21 [==============================] - 1s 6ms/step - loss: 1.0026 - accuracy: 0.5221 - val_loss: 0.8505 - val_accuracy: 0.7417
Epoch 2/10
21/21 [==============================] - 0s 2ms/step - loss: 0.7483 - accuracy: 0.7848 - val_loss: 0.6517 - val_accuracy: 0.7667
Epoch 3/10
21/21 [==============================] - 0s 2ms/step - loss: 0.5695 - accuracy: 0.8392 - val_loss: 0.4996 - val_accuracy: 0.8306
Epoch 4/10
21/21 [==============================] - 0s 2ms/step - loss: 0.4171 - accuracy: 0.8971 - val_loss: 0.3601 - val_accuracy: 0.9306
Epoch 5/10
21/21 [==============================] - 0s 2ms/step - loss: 0.2807 - accuracy: 0.9730 - val_loss: 0.2246 - val_accuracy: 0.9917
Epoch 6/10
21/21 [==============================] - 0s 2ms/step - loss: 0.1574 - accuracy: 0.9956 - val_loss: 0.1117 - val_accuracy: 0.9944
Epoch 7/10
21/21 [==============================] - 0s 2ms/step - loss: 0.0770 - accuracy: 0.9985 - val_loss: 0.0553 - val_accuracy: 1.0000
Epoch 8/10
21/21 [==

### Test 4. Epochs=7, batch_size=350, validation_split=0.30


In [226]:
model = Sequential()
model.add(Dense(32, activation='relu', input_dim=5))

model.add(Dense(32, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(3, activation='softmax'))

model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=7, batch_size=350, validation_split=0.30)
loss, accuracy = model.evaluate(X_test, y_test)
print('loss: '+ str(loss))
print('accuracy: '+ str(accuracy*100))

Epoch 1/7
5/5 [==============================] - 1s 28ms/step - loss: 1.0660 - accuracy: 0.5530 - val_loss: 1.0430 - val_accuracy: 0.6653
Epoch 2/7
5/5 [==============================] - 0s 6ms/step - loss: 1.0260 - accuracy: 0.7268 - val_loss: 1.0042 - val_accuracy: 0.7542
Epoch 3/7
5/5 [==============================] - 0s 6ms/step - loss: 0.9842 - accuracy: 0.7976 - val_loss: 0.9607 - val_accuracy: 0.7861
Epoch 4/7
5/5 [==============================] - 0s 6ms/step - loss: 0.9357 - accuracy: 0.8393 - val_loss: 0.9096 - val_accuracy: 0.8208
Epoch 5/7
5/5 [==============================] - 0s 6ms/step - loss: 0.8793 - accuracy: 0.8655 - val_loss: 0.8517 - val_accuracy: 0.8431
Epoch 6/7
5/5 [==============================] - 0s 6ms/step - loss: 0.8177 - accuracy: 0.8893 - val_loss: 0.7887 - val_accuracy: 0.8708
Epoch 7/7
19/19 [==============================] - 0s 629us/step - loss: 0.6970 - accuracy: 0.9367
loss: 0.6970193386077881
accuracy: 93.66666674613953


### Test 5. Epochs=7, batch_size=300, validation_split=0.20


In [227]:
model = Sequential()
model.add(Dense(32, activation='relu', input_dim=5))

model.add(Dense(32, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(3, activation='softmax'))

model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=7, batch_size=300, validation_split=0.20)
loss, accuracy = model.evaluate(X_test, y_test)
print('loss: '+ str(loss))
print('accuracy: '+ str(accuracy*100))

Epoch 1/7
7/7 [==============================] - 1s 18ms/step - loss: 1.1919 - accuracy: 0.5130 - val_loss: 1.1205 - val_accuracy: 0.5604
Epoch 2/7
7/7 [==============================] - 0s 4ms/step - loss: 1.0851 - accuracy: 0.5536 - val_loss: 1.0204 - val_accuracy: 0.5021
Epoch 3/7
7/7 [==============================] - 0s 4ms/step - loss: 0.9819 - accuracy: 0.5349 - val_loss: 0.9202 - val_accuracy: 0.6354
Epoch 4/7
7/7 [==============================] - 0s 4ms/step - loss: 0.8792 - accuracy: 0.7453 - val_loss: 0.8175 - val_accuracy: 0.7771
Epoch 5/7
7/7 [==============================] - 0s 4ms/step - loss: 0.7746 - accuracy: 0.8234 - val_loss: 0.7171 - val_accuracy: 0.7812
Epoch 6/7
7/7 [==============================] - 0s 4ms/step - loss: 0.6743 - accuracy: 0.8297 - val_loss: 0.6217 - val_accuracy: 0.8021
Epoch 7/7
19/19 [==============================] - 0s 636us/step - loss: 0.5041 - accuracy: 0.8867
loss: 0.50412917137146
accuracy: 88.66666555404663
